version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: elixir:1.6.0
        environment:
          - MIX_ENV: test
      - image: postgres:9.6.6
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      - run: mix coveralls.circle
