use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# ComeBikeWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :ComeBike, ComeBikeWeb.Endpoint,
  secret_key_base: "${SECRET_KEY_BASE}",
  load_from_system_env: true,
  url: [host: "${PHX_HOST}", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# config :sentry,
#   dsn: "${SENTRY_DNS}",
#   environment_name: :prod,
#   enable_source_code_context: true,
#   root_source_code_path: File.cwd!(),
#   tags: %{
#     env: "production"
#   },
#   included_environments: [:prod]

# Do not print debug messages in production
config :logger, level: :info

config :ComeBike, ComeBike.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${DB_USER}",
  password: "${DB_PASS}",
  database: "${DB}",
  pool_size: 15
